language: java
jdk:
  - openjdk8

branches:
  only:
    - aws_version

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      yourmineService@gmail.com